require("mulabeg.plugins-setup")
require("mulabeg.core.options")
require("mulabeg.core.keymaps")
require("mulabeg.core.colorscheme")
require("mulabeg.plugins.comment")
require("mulabeg.plugins.nvim-tree")
require("mulabeg.plugins.lualine")
require("mulabeg.plugins.telescope")
require("mulabeg.plugins.nvim-cmp")
require("mulabeg.plugins.lsp.mason")
require("mulabeg.plugins.lsp.lspsaga")
require("mulabeg.plugins.lsp.lspconfig")
require("mulabeg.plugins.lsp.null-ls")
require("mulabeg.plugins.autopairs")
require("mulabeg.plugins.treesitter")
require("mulabeg.plugins.gitsigns")

